spring.application.name=Chat-O-Mania
spring.datasource.url=jdbc:postgresql://localhost:5433/chatomaniadb
spring.datasource.username=postgres
spring.datasource.password=Sabu1234@.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.web=DEBUG
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_CLOUD_KEY}
cloudinary.api-secret=${CLOUDINARY_CLOUD_KEY_SECRET}